# Utiliza una imagen base de Node.js
FROM node:18-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el package.json y package-lock.json y luego instala las dependencias
RUN npm install -g npm@10.8.2
RUN npm install -g @nestjs/cli
RUN nest new api-rest

# Copia el resto de los archivos del proyecto
# COPY . .

# Exponer el puerto donde escuchará la aplicación (ajusta según tu configuración)
EXPOSE 8080

# Comando para iniciar la aplicación
CMD ["npm", "run", "start"]