services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: pass123
    volumes:
      - /home/poncho/Dev/devops/ejemplo-1/bd/postgres_data:/var/lib/postgresql/data
      - /home/poncho/Dev/devops/ejemplo-1/bd/postgres_backup:/var/lib/postgresql/backup
    ports:
      - "5432:5432"
  api-nest:
    build:
      context: /home/poncho/Dev/devops/ejemplo-1/api-rest
      dockerfile: Dockerfile.dev
    volumes:
      - /home/poncho/Dev/devops/ejemplo-1/api-rest:/app
    ports:
      - "3000:3000"

